### ISSUE TITLE
Target ES2018 or ES2019

### ISSUE THREAD

**Issue by novemberborn** [connor4312/cockatiel#10]
TypeScript is currently targeting ES2015 environments. This means language features like `async`/`await` are being transpiled.

If the supported Node.js version is 12 (#9), targeting ES2019 removes all this transpilation.

Let me know if this is something you'd like and I can submit a PR.

**Comment by connor4312** [comment]
Sorry, missed this issue. I'm fine charging the target to whatever features Node 10 supports.
