### ISSUE TITLE
`retry` causes Cloudflare workers runtime to collapse

### ISSUE THREAD

**Issue by roziscoding** [connor4312/cockatiel#105]
Currently, calling `retry` generates a warning which prevents the cloudflare workers runtime from running.

This is a simple repro:
```js
// repro.js
import { retry } from 'cockatiel'

retry()
```

Running with `npx wrangler dev repro.ts` generates the following error:

```
✘ [ERROR] service core:user:worker: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/

    at null.<anonymous> (core:user:worker:433:28)
    at null.<anonymous> (core:user:worker:684:3)



✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.
```

I have not tested other functions from this library to know if they cause the same problem

**Comment by connor4312** [comment]
Looks like a bug in workers that disallows a global usage of AbortController/AbortSignal. I would open an issue with them.

I would also take a PR that works to fix it, but personally I have quite low motivation to change a perfectly valid use of language features to cater to capricious choices of random runtimes 😛

**Comment by roziscoding** [comment]
Very valid. I'll open an issue over there.
Thanks for replying :)
