### ISSUE TITLE
fallback with other policies

### ISSUE THREAD

**Issue by willsoto** [connor4312/cockatiel#19]
Is it possible to use [`Policy.fallback`](https://github.com/connor4312/cockatiel#policyfallbackvalueorfactory) with other policies via `Policy.wrap`?

Here is my use case: I would like retry a particular API call up to 3 times, if those 3 attempts fail, I would like to use the `fallback` value. As I understand `wrap`, it will call through to each wrapped policy (which makes sense). But this means that on the first attempt, the `fallback` will be triggered and there will be no more attempts. 

Here is some code to show what I am trying to achieve:

```ts
import { Policy } from 'cockatiel';

// Basically copied from the README
export const retry = Policy.handleAll().retry().attempts(3).exponential({
  maxDelay: 10000,
});

const fallback = Policy.handleType(Error, (error) => {
  return error.statusCode === 500;
}).fallback({});

const policy = Policy.wrap(retry, fallback);

class Client {
  @Policy.use(policy)
  apiCall() {
    // make an api call 
  }
}
```

If `fallback` cannot be mixed with other policies like this, are there any alternatives?

**Comment by ekillops** [comment]
I believe you will need `fallback` to be the first policy you pass into the `wrap`. See the Polly docs for reference on how `wrap` executes: https://github.com/App-vNext/Polly/wiki/PolicyWrap

**Comment by connor4312** [comment]
Yep, exactly. Let me know if that fixes it for you.

**Comment by willsoto** [comment]
@ekillops You are correct. Thank you!
