### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by HonzaMac** [connor4312/cockatiel#20]
We would like to start monitor of circuit breakers and retry's and timeouts in production.

I like this library the most from others but I am missing a way how to monitor current state.

I've tried to get at least `breaker.stats` and some `onRetry` and other, but would be better to have more holistic way how to get this events and state out of cockatiel.

Is there a way how to get this statistics? 

i.e. here is [some inspiration](https://www.npmjs.com/package/levee) in Levee project. 

Example how such output could one day look.
[Article from Hystrix](https://netflixtechblog.com/making-the-netflix-api-more-resilient-a8ec62159c2d) with video. 

![image](https://user-images.githubusercontent.com/3055648/83811672-86910400-a6ba-11ea-9495-c65c40e7ca9f.png)
This image actually aggregates all instances of circuit breaker per concrete service.

I can image taking this information with every request (or batching can be done by another tool).
I am thinking now about this metrics:
- time to process request
- state - open, closed, half-open
- end state of request - timedout/sucess/failed
- 1,2,3 retry of request

> As a side note: I want to integrate it into Grafana using InfluxDb (but this is not important)
> Example of [Grafana dashboard](https://medium.com/@gopalkrushnapattanaik/creating-fault-tolerant-services-using-resilience4j-888d72a4fc0e)

**Comment by HonzaMac** [comment]
What do you think @connor4312 ?

**Comment by connor4312** [comment]
Apologies, been busy. I will look into this more deeply this weekend.

**Comment by connor4312** [comment]
The circuit breaker now includes a general `onStateChange` callback, and all policies include `onSuccess` and `onFailure` events, which are called with information about the function run duration. I think this should be sufficient to get the monitoring you're after.

Levee actually includes a basic statistics store, but I think this is out of scope for the library--there are numerously, differently configurable ways to collect call duration, for instance, which can be handled better by a specific telemetry library.

**Comment by HonzaMac** [comment]
Thank you @connor4312  for this improvement 👏. This will enable monitoring what I am looking for, will try it in upcoming week.

Great work 💪🏼
