### ISSUE TITLE
Error:  Cannot read property 'bigint' of undefined

### ISSUE THREAD

**Issue by conradob** [connor4312/cockatiel#21]
Greetings,
I'm trying to create a wrapper for HTTP requests but getting this error when I use `.attempts(3)` or `.exponential()` from `retry()` policy.

```
Unhandled Rejection (TypeError): Cannot read property 'bigint' of undefined
makeStopwatch
src/common/Executor.ts:19
```

With just `Policy.handleAll().retry().execute(...)` it works properly.

I'm running in the browser and using `axios` to make the HTTP request:

```
const request = (method) => async (...args) =>
  await Policy.handleAll()
    .retry()
    .attempts(3)
    .exponential()
    .execute(() => axios[method](...args));
```

**Comment by connor4312** [comment]
Thanks, published 1.0.1 with a fix
