### ISSUE TITLE
[Question] Cancel a retry policy

### ISSUE THREAD

**Issue by conradob** [connor4312/cockatiel#25]
Sorry to raise an issue just to ask a question but is there a way to cancel a retry policy?

The use case I'm trying to achieve is if the user attempts to redo the same action that was being retried, would like to cancel the current retry and then create a new retry with the updated data.

Is it possible?

Thanks for the terrific work with this tool.

**Comment by connor4312** [comment]
Not right now. Something I've been meaning to do has been allowing you to pass a cancellation token through `IPolicy.execute`. I'll add that tonight.

**Comment by connor4312** [comment]
Added: https://github.com/connor4312/cockatiel#retryexecutefn-cancellationtoken

Cancelling the token will cause the last error emitted by the function to be bubbled.

**Comment by conradob** [comment]
I'm not sure if I'm missing something but I couldn't make the retry policy stop using the cancellation token.
 
Here follow the example of a simple experiment I did to cancel a retry after 5 attempts.
> I know cockatiel provide retry policy attempts but this is just a figurative test to play with the cancellation token

https://github.com/conradob/cockatiel-retry-playground

**Comment by connor4312** [comment]
You need to pass in the cancellation token, not the source:

```diff
diff --git a/index.js b/index.js
index ad8a922..32d3c1e 100644
--- a/index.js
+++ b/index.js
@@ -25,7 +25,7 @@ const main = async () => {
 
   const result = await retryPolicy.execute(
     () => failCallback(),
-    cancellationTokenSource
+    cancellationTokenSource.token
   )

   console.log(result)

```

**Comment by conradob** [comment]
That is it. 
Perfect. Thanks for all your support.
