### ISSUE TITLE
Add docs to ConsecutivePolicy ctor and args

### ISSUE THREAD

**Issue by Tyriar** [connor4312/cockatiel#26]
Currently docs are on the class, not the ctor:

![image](https://user-images.githubusercontent.com/2193314/87433525-4026a300-c59e-11ea-86d4-2027ba29062a.png)
![image](https://user-images.githubusercontent.com/2193314/87433544-4583ed80-c59e-11ea-88ca-3e9f464a37d9.png)

**Comment by connor4312** [comment]
Huh, TIL that I've been living my life wrong for years
