### ISSUE TITLE
Exponential Backoff + Circuit breaker

### ISSUE THREAD

**Issue by mmadson** [connor4312/cockatiel#36]
In the docs it says that exponential backoff and circuit breaker are friends, but I didn't see an example of using them together. Do I need to combine a retry policy with a circuit breaker policy to give the circuit breaker the exponential backoff behavior, or is there a way to specify the backoff policy directly on the circuit breaker?

**Comment by connor4312** [comment]
Yes, usually you want to wrap a circuit breaker inside of a backoff. E.g.

```
// Create a retry policy that'll try whatever function we execute 3
// times with a randomized exponential backoff.
const retry = Policy.handleAll().retry().attempts(3).exponential();

// Create a circuit breaker that'll stop calling the executed function for 10
// seconds if it fails 5 times in a row. This can give time for e.g. a database
// to recover without getting tons of traffic.
const circuitBreaker = Policy.handleAll().circuitBreaker(10 * 1000, new ConsecutiveBreaker(5));

// Combine these! Create a policy that retries 3 times, calling through the circuit breaker
const retryWithBreaker = Policy.wrap(retry, circuitBreaker);
```

The retry gives you protection against transient issues, and you generally want to use it outside of the circuit breaker in order to be able to correctly break at certain threshold and do the 'half-open' tests.

**Comment by mmadson** [comment]
Thank you very much for the clarification!
