### ISSUE TITLE
add deno support ?

### ISSUE THREAD

**Issue by jd1378** [connor4312/cockatiel#39]
is it possible to have this on https://deno.land/x ?

**Comment by connor4312** [comment]
I've done so.

**Comment by jd1378** [comment]
hmm, today I came to test the usage on deno, and I can't import it, probably because the imports do not include file extensions, which is required on deno
can you check it out ?

**Comment by jd1378** [comment]
Im not sure if it's that easy to get it working, but ... I have an idea that *may* worth trying if you have time:
Create another repo and move the webhook there
Setup it in a way that running a workflow clones this repo
moves `src/*` to root folder of the new repo (replace existing files of the repo on next runs)
rename `index.ts` to `mod.ts`
adds file extentions to imports everywhere (maybe [denoify](https://www.npmjs.com/package/denoify)?)
commit the new changes with something like [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action)
create a tag same as latest tag of the cloned repo
and make sure workflow runs only per tag.

you can either trigger workflows manually or [using a `repository_dispatch` event](http://blog.marcnuri.com/triggering-github-actions-across-different-repositories/)

**Comment by andrinheusser** [comment]
I've set up https://deno.land/x/deno_cockatiel which, at first glance, seems to work
