### ISSUE TITLE
handleWhenResult Policy incorrectly called handleResultWhen in documentation

### ISSUE THREAD

**Issue by moberegger** [connor4312/cockatiel#41]
The documentation says there is a policy called [handleResultWhen](https://github.com/connor4312/cockatiel#policyhandleresultwhenfilter), but it is actually called [handleWhenResult](https://github.com/connor4312/cockatiel/blob/863db9bd368923d6a9a47091d7978f57a53796b5/src/Policy.ts#L253).

**Comment by connor4312** [comment]
Thanks for the issue!

**Comment by moberegger** [comment]
Well, that was fast!
