### ISSUE TITLE
Is this library tree-shakable?

### ISSUE THREAD

**Issue by rmeshksar** [connor4312/cockatiel#50]
Hi,
Thanks for the great library.
I used this library for the first time in my Angular application and it works great.

In my example, I only import Policy and retry but noticed even in production build the whole library is in the generated code.

My question is that if this library is tree-shakable and if there is anything I need to do.

Thanks.

**Comment by connor4312** [comment]
It's tree shakable, due to the structure (which mirrors .NET Polly) policies don't get shaken out -- your code references Policy, which in turn is a factory for basically everything else. I want to tackle this for the 3.0 release. This might involve an API that looks something more like...

```ts
import { retry, handleType } from 'cockatiel';

const policy = retry(handleType(NetworkError)).attempts(3);
```
