### ISSUE TITLE
Cockatiel 3.0 ChangeLog and Notes

### ISSUE THREAD

**Issue by jaredwray** [connor4312/cockatiel#66]
Hi @connor4312 👋  - we use Cockatiel for our `etcd` adapter at Keyv (https://github.com/jaredwray/keyv) and it looks like with `3.0.0` things are not working as they did before. 

```javascript
		const policy = Policy.handleAll().retry();
		policy.onFailure(error => {
			this.emit('error', error.reason);
		});
		this.client = new Etcd3(options = {hosts: this.opts.url,
			faultHandling: {
				host: () => policy,
				global: policy,
			},
		});
```

This code example is now failing when we upgrade. A couple of questions around this is if you have updated release notes as the latest (https://github.com/connor4312/cockatiel/releases) is showing `2.0.0`. 

If there is something you can point me to that would be great. ❤️

**Comment by connor4312** [comment]
This is in the changelog.md: https://github.com/connor4312/cockatiel/blob/master/changelog.md

Thanks for upgrading, let me know if you run into any problems 😄

**Comment by jaredwray** [comment]
@connor4312 - thanks so much!
