### ISSUE TITLE
Dynamic `halfOpenAfter` for circuit breakers

### ISSUE THREAD

**Issue by nth-commit** [connor4312/cockatiel#68]
Is there any guidance around getting this to work?

I'm heavily hitting an API that I don't control, nor have much insight of their (seemingly inconsistent) rate-limiting functionality.

I would love it if I could do write a back-off function to workaround this, that grows with the number of attempts.

**Comment by connor4312** [comment]
You're asking how to get "[d]ynamic halfOpenAfter for circuit breakers" to work -- I'm not sure what you mean by this, can you elaborate?

**Comment by nth-commit** [comment]
I want the circuit breaker timeout to be derived from number of attempts, rather than a constant value.

At the moment, this is my code:

```
const handleRateLimitations = handleWhen(isRateLimitationError)
const rateLimitationCircuitBreakerPolicy = circuitBreaker(handleRateLimitations, {
  breaker: new ConsecutiveBreaker(1),
  halfOpenAfter: 5 * 60 * 1_000,
})
```

Ideally, I want something like this:

```
const handleRateLimitations = handleWhen(isRateLimitationError)
const rateLimitationCircuitBreakerPolicy = circuitBreaker(handleRateLimitations, {
  breaker: new ConsecutiveBreaker(1),
  halfOpenAfter: new ExponentialBackoff({ maxDelay: 5 * 60 * 1000 }),
})
```

Where the attempt number that is passed to the backoff function is the number of consecutive times the circuit-breaker has gone from half-open (or closed) to open. The circuit breaker moving back to the closed state would reset the attempts to 0.

**Comment by connor4312** [comment]
I see. I think that makes sense. PR's welcome, or I will get to this at some point.
