### ISSUE TITLE
Not work with IE11 on babel7.7/webpack3

### ISSUE THREAD

**Issue by xyarsg** [connor4312/cockatiel#7]
This project looks so cool. Thank you for your effort.

But when I just have imported cockatiel on IE11 on babel7.7/webpack3,
```
// const { Policy } = require('cockatiel');
import { Policy } from 'cockatiel';
```
following errors are raised.

>SCRIPT1002: Syntax error
>File: vendor.ba5e24009865b3d08bdb.js, Line: 74, Column: 46326
```
class r extends Error{constructor(t="Operation cancelled"){super(t),this.message=t}}const i={dispose:()=>void 0};var o,a;(a=o||(o={})).once=((t,e)=>{let n,r=!1;return n=t(t=>{e(t),n?n.dispose():r=!0}),r?(n.dispose(),i):n}),a.toPromise=((t,e)=>e?e.isCancellationRequested?Promise.reject(new r):new Promise((n,i)=>{const o=a.once(e.onCancellation ...
```
>SCRIPT5007: Unable to get property 'call' of undefined or null reference
>File: manifest.a7a4b6dcafd233ff7c65.js, Line: 1, Column: 399
```
		return module.exports;
 	}

 	// This file contains only the entry chunk.
 	// The chunk loading function for additional chunks
 	__webpack_require__.e = function requireEnsure(chunkId) {
```

I need to work with IE11/chrome/safari/... .
Cockatiel works with the others browser well.

Have you a plan to work with IE11? or just my setting is wrong? (like webpack/babel version)

Regards.

**Comment by connor4312** [comment]
Sorry, I don't intend to support IE11 in this library. You may be able to get it to work by running babel on Cockatiel, though.
