### ISSUE TITLE
Request gets aborted after success when using Timeout

### ISSUE THREAD

**Issue by tomvardasca** [connor4312/cockatiel#72]
Hi,

Thank you a lot for this library!

Looked at the code in https://github.com/connor4312/cockatiel/blob/master/src/TimeoutPolicy.ts#L100 and noticed that we trigger an `abort` in the `finally`. 
This behavior makes this signal unusable for the `fetch` API https://developer.mozilla.org/en-US/docs/Web/API/AbortController#instance_methods

>[AbortController.abort()](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort) 
> Aborts a DOM request before it has completed. This is able to abort [fetch requests](https://developer.mozilla.org/en-US/docs/Web/API/fetch), consumption of any response bodies, and streams.

This way in node.js when we try to consume the response. It is already aborted.

Would it be possible to have an option to skip this?

Kind Regards,
Tomé

**Comment by connor4312** [comment]
Changing this behavior would be breaking, but in 3.1.0 I've added a new option you can use like so:

```js
timeout(
  () => fetch('https://example.com'),
  { strategy: 'aggressive', abortOnReturn: false /* <-- new */ },
)
```

**Comment by tomvardasca** [comment]
Thank you for adding an option!
