### ISSUE TITLE
[Question] Execution prevented because the circuit breaker is open

### ISSUE THREAD

**Issue by JobaDiniz** [connor4312/cockatiel#83]
I'm trying the following retry policy

```typescript
timeout = timeout ?? 1000 * 30; //30s
        const maxAttempts = 5;
        //const policy = handleType(BrokenCircuitError).orWhenResult(element => element == undefined);
        const policy = handleAll.orWhenResult(element => element == undefined);
        const breakerPolicy = circuitBreaker(policy, { halfOpenAfter: timeout / maxAttempts, breaker: new ConsecutiveBreaker(maxAttempts / 2) });
        const retryPolicy = retry(policy, { maxAttempts: maxAttempts, backoff: new ExponentialBackoff({ maxDelay: timeout }) });

        const element = await wrap(retryPolicy, breakerPolicy).execute((context) => {
            //some code that returns an HTMLElement or undefined...
            return element;
        });
```

But it fails with `Execution prevented because the circuit breaker is open`.

What's wrong?

**Comment by connor4312** [comment]
I don't see anything inherently wrong with that code.

**Comment by JobaDiniz** [comment]
I'm stuck :(

**Comment by JobaDiniz** [comment]
I increased the `initialDelay` of the `ExponentialBackoof` to 500ms and it stopped giving me that error.

**Comment by connor4312** [comment]
I need more information about what you're trying to do and what you expect to see to offer any advice / bug fix

**Comment by JobaDiniz** [comment]
This is the minimal repo I could produce: https://github.com/JobaDiniz/cockatiel-retry

It's a chrome extension.

The readme says how to build it.

After build and loading into chrome, just click the "icon" extension button. There will be times when it will work. There will be times that it won't. Inspecting the Console you will see error.

When clicking the extension icon, it is supposed to:
1. automatically click the "initiate request" button
2. wait, using retries, for the last card to be rendered
3. type in the input of the last rendered card.

**Comment by connor4312** [comment]
That seems pretty expected. With maxAttempts = 4, the circuit breaker is set to open after 2 failed attempts. That'll happen after about 500ms--the first check fails, then the next retry 500ms later will fail. Then after the next two attempts, bounced because the circuit breaker's half open time probably wasn't reached yet, the retry will give up.

**Comment by JobaDiniz** [comment]
So, how do I create a retry that won't fail on exception?

A retry with exponential backoof + a circuit breaker?

**Comment by connor4312** [comment]
If you don't want it to ever stop retrying, set `maxAttempts: Infinity`

**Comment by JobaDiniz** [comment]
I want to stop retrying, but not with an error. I don't understand why it fails with exception.
I come from `dotnet`, and maybe I'm using this `typescript` version wrong.

I want something like: retry, wait, retry, wait longer, retry again.

By combining exponential backoff + circuit breaker, I thought I would achieve that.

**Comment by connor4312** [comment]
> I want to stop retrying, but not with an error.

Then you can use a try/catch. There's no mode in this library where `retry` would fail silently/return undefined if an inner function threw an error.

> I want something like: retry, wait, retry, wait longer, retry again. That is, if the first couple of attempts fail, wait longer for the next ones.

That is what's happening, until the number of retries is exhausted. After 4 attempts, it allows the inner error/invalid result to go through. If you want to do this for longer, raise the number of maxAttempts.

**Comment by JobaDiniz** [comment]
>Then you can use a try/catch. There's no mode in this library where retry would fail silently/return undefined if an inner function threw an error.

I thought the `handleAll` would catch all errors, no?

**Comment by connor4312** [comment]
`handleAll` does catch all errors, but when `retry` exhausts all of its attempts, then the last error/errorful result is propagated. If the last error is one from the circuit breaker, then that's the error that gets thrown.
