### ISSUE TITLE
Signal reason not propagated in timeout cancellation

### ISSUE THREAD

**Issue by cnoelle** [connor4312/cockatiel#99]
Thank you for this useful library. I came across an unexpected error message when cancelling a timeout execution via AbortSignal. 

In the following code a signal is passed as second argument to `TimeoutPolicy.execute()`. When aborting the signal, the returned promise from execute is cancelled with an entirely different error, `TaskCancelledError: Operation timed out after 5000ms`, although no timeout occurred.

```javascript
import {timeout, TimeoutStrategy} from "cockatiel";

const fetchResult = async (signal) => {
    await new Promise(resolve => setTimeout(resolve, 1000));
    return fetch("https://www.google.com", {signal: signal});
};
const policy = timeout(5000, {strategy: TimeoutStrategy.Aggressive});
const ctrl = new AbortController();
const result = policy.execute(ctx => fetchResult(ctx.signal), ctrl.signal);
ctrl.abort(new Error("Fetch cancelled"));
result
    .then(r => console.log("Promise unexpectedly completed", r))
    /**
     * Expected: logs "Execution failed Error: Fetch cancelled"
     * Actual: logs "Execution failed TaskCancelledError: Operation timed out after 5000ms"
     */
    .catch(e => console.log("Execution failed", e)); 
```

The same code for cooperative timeout strategy gives the generic error `DOMException [AbortError]: This operation was aborted`, instead, which is more accurate than the timeout message, but still missing the reason provided. Replacing the timeout policy with bulkhead, on the other hand, gives the expected result.

**Comment by cnoelle** [comment]
Part of the solution might be to pass on the signal reason in the `deriveAbortController` function here: https://github.com/connor4312/cockatiel/blob/975fc44f1a865199c5530623f300200825dcb136/src/common/abort.ts#L24-L30

Something along the line of 

```javascript
if (signal.aborted) {
    ctrl.abort(signal.reason);
} else {
    signal.addEventListener("abort", () => ctrl.abort(signal.reason));
}
```

**Comment by connor4312** [comment]
`TimeoutStrategy.Aggressive` does not wait for the implementation to throw an error, see [docs](https://github.com/connor4312/cockatiel?tab=readme-ov-file#timeoutduration-strategy):

>  In aggressive timeouts, we'll immediately throw a TaskCancelledError when the timeout is reached, in addition to marking the passed token as failed.

**Comment by cnoelle** [comment]
I see. However, getting a timeout error when the user cancelled a request seems wrong and misleading. Would it be possible to throw a TaskCancelledError with `cause` field set to the original cancellation reason instead (resp. the generic `DOMException [AbortError]: This operation was aborted` if no reason was given), plus an adapted error message? This way it would still be in line with the documentation but also provide the actual cause of the rejection.

**Comment by cnoelle** [comment]
By the way, the documentation also states that *If cancellation is requested on the parent abort signal provided as the second argument to execute(), the cancellation will be propagated.* (https://github.com/connor4312/cockatiel/?tab=readme-ov-file#timeoutexecutefn-signal). I would expect in this case that also the reason is propagated, but this is currently not the case, neither in cooperative nor aggressive mode.
